-- ============================================================================
-- JalKal (जलकाल) - Urban Flood Nowcasting & Safe Navigation Engine
-- PostGIS 3.4 + pgRouting Database Initialization & Schema DDL
-- Problem Statement: SIH26085 (MoES / NCMRWF)
-- ============================================================================

-- 1. Enable Spatial & Graph Extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "postgis";
CREATE EXTENSION IF NOT EXISTS "pgrouting";

-- 2. Clean existing tables if needed
DROP TABLE IF EXISTS live_inundation_logs CASCADE;
DROP TABLE IF EXISTS drain_conduits CASCADE;
DROP TABLE IF EXISTS drain_nodes CASCADE;
DROP TABLE IF EXISTS road_segments CASCADE;

-- 3. Drainage Infiltration & Catchment Nodes (Manholes / Inlets)
-- Models ground elevation, invert base level, catchment catchment basin area,
-- and curb length for stormwater capture.
CREATE TABLE drain_nodes (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    node_code VARCHAR(64) UNIQUE NOT NULL,
    geom GEOMETRY(Point, 4326) NOT NULL,
    z_ground NUMERIC(8, 3) NOT NULL,            -- Ground surface elevation (m AMSL)
    z_invert NUMERIC(8, 3) NOT NULL,            -- Sump / pipe invert elevation (m AMSL)
    basin_area_m2 NUMERIC(12, 2) NOT NULL,      -- Sub-catchment tributary area draining into inlet
    curb_length_m NUMERIC(6, 2) DEFAULT 3.0,    -- Street inlet curb opening length
    c_runoff NUMERIC(4, 2) DEFAULT 0.90,        -- Impervious runoff coefficient (asphalt/concrete)
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT check_elevations CHECK (z_ground >= z_invert)
);

-- 4. Underground Drainage Conduits (Pipes & Box Culverts)
-- Connects drain_nodes in a directed or bidirectional drainage network.
CREATE TABLE drain_conduits (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    conduit_code VARCHAR(64) UNIQUE NOT NULL,
    source_node UUID NOT NULL REFERENCES drain_nodes(id) ON DELETE CASCADE,
    target_node UUID NOT NULL REFERENCES drain_nodes(id) ON DELETE CASCADE,
    geom GEOMETRY(LineString, 4326) NOT NULL,
    diameter_m NUMERIC(6, 3) NOT NULL,          -- Pipe internal diameter or hydraulic equivalent (m)
    length_m NUMERIC(10, 3) NOT NULL,           -- Conduit horizontal length (m)
    manning_n NUMERIC(6, 4) DEFAULT 0.014,      -- Manning roughness coeff (0.012 smooth concrete to 0.016 brick)
    clogging_ratio NUMERIC(4, 3) DEFAULT 0.000, -- Dynamic clogging factor alpha [0.0 = clear, 1.0 = blocked]
    slope NUMERIC(8, 5) DEFAULT 0.005,          -- Bed slope (m/m)
    design_q_m3s NUMERIC(10, 4),                -- Max nominal gravity conveyance capacity (m3/s)
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT check_clogging CHECK (clogging_ratio >= 0.0 AND clogging_ratio <= 1.0)
);

-- 5. Street & Road Network Segments (OSM Derived Road Topologies)
-- Road segments intersected with local drainage catchments and elevation profiles.
CREATE TABLE road_segments (
    id BIGINT PRIMARY KEY,                      -- Compatible with OSM Way ID
    osm_id BIGINT NOT NULL,
    road_name VARCHAR(255) DEFAULT 'Unnamed Street',
    highway_type VARCHAR(64) DEFAULT 'residential',
    geom GEOMETRY(LineString, 4326) NOT NULL,
    base_speed_kmh NUMERIC(5, 2) DEFAULT 40.0,
    length_m NUMERIC(10, 3) NOT NULL,
    source_vertex BIGINT,                       -- pgRouting source node
    target_vertex BIGINT,                       -- pgRouting target node
    z_elevation NUMERIC(8, 3) DEFAULT 10.0,     -- Average street surface elevation
    curb_height_m NUMERIC(4, 2) DEFAULT 0.15,   -- Curb depth before water spills to properties
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 6. Dynamic Inundation Logs (Time-Horizon Slices: T+0, T+15, ..., T+180 min)
-- Stores predicted street water depths generated by the Hybrid Physics-AI solver.
CREATE TABLE live_inundation_logs (
    id BIGSERIAL PRIMARY KEY,
    road_segment_id BIGINT NOT NULL REFERENCES road_segments(id) ON DELETE CASCADE,
    timestamp_horizon_min INT NOT NULL,         -- 0, 15, 30, 45, 60, ..., 180 minutes
    water_depth_cm NUMERIC(6, 2) NOT NULL,      -- Water depth above street crown (cm)
    flow_velocity_ms NUMERIC(5, 2) DEFAULT 0.0, -- Surface flow velocity (m/s)
    status VARCHAR(32) NOT NULL,                -- 'PASSABLE' (<10cm), 'SLOW' (10-25cm), 'IMPASSABLE' (>25cm)
    hazard_penalty NUMERIC(8, 2) DEFAULT 1.0,   -- A* impedance factor
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT check_horizon CHECK (timestamp_horizon_min >= 0 AND timestamp_horizon_min <= 360),
    CONSTRAINT check_status CHECK (status IN ('PASSABLE', 'SLOW', 'IMPASSABLE'))
);

-- 7. High-Performance Spatial Indexes (GiST)
CREATE INDEX idx_drain_nodes_geom ON drain_nodes USING GIST(geom);
CREATE INDEX idx_drain_conduits_geom ON drain_conduits USING GIST(geom);
CREATE INDEX idx_road_segments_geom ON road_segments USING GIST(geom);
CREATE INDEX idx_inundation_road_horizon ON live_inundation_logs(road_segment_id, timestamp_horizon_min);
CREATE INDEX idx_inundation_horizon ON live_inundation_logs(timestamp_horizon_min);
CREATE INDEX idx_conduits_source ON drain_conduits(source_node);
CREATE INDEX idx_conduits_target ON drain_conduits(target_node);

-- 8. Spatial View: Live Flooded Roadways with Geometries for Instant MVT / GeoJSON serving
CREATE OR REPLACE VIEW view_flooded_roads_nowcast AS
SELECT 
    l.id AS log_id,
    l.timestamp_horizon_min,
    l.water_depth_cm,
    l.flow_velocity_ms,
    l.status,
    l.hazard_penalty,
    r.id AS road_id,
    r.osm_id,
    r.road_name,
    r.highway_type,
    r.base_speed_kmh,
    r.length_m,
    r.geom
FROM live_inundation_logs l
JOIN road_segments r ON l.road_segment_id = r.id;

-- 9. pgRouting Topology Helper Function
CREATE OR REPLACE FUNCTION pgr_build_road_topology()
RETURNS text AS $$
BEGIN
    -- Builds vertices and assigns source_vertex and target_vertex on road_segments
    PERFORM pgr_createTopology('road_segments', 0.0001, 'geom', 'id');
    RETURN 'SUCCESS';
END;
$$ LANGUAGE plpgsql;

